### ISSUE TITLE
An error in doc

### ISSUE THREAD

**Issue by SMMNECQK** [ninemoreminutes/django-admin-object-actions#2]
Instead of `from admin_model_actions.admin import` it should be `from admin_object_actions.admin import ` in the doc.

PS: Love your plugin very very very much.
Among those plugins named as 'django-object-actions' or 'django-admin-actions', I find this one is exactly what I want.

PSS: I also find [django-object-actions](https://github.com/crccheck/django-object-actions) quite useful.
It would be nice if you could absorb its features, such as a button on the right top of a model to batch execute queryset.

**Comment by cchurch** [comment]
Fixed in 33fcab0112d6018418736b67d8299c7d219c31b6.
