### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by atar-axis** [ninemoreminutes/django-admin-object-actions#7]
Isn't the buttons rendered by default - I followed the instructions but the button does not appear!
Do I have to add it to the "list_display" list? If yes, how?

**Comment by cchurch** [comment]
You do have to add `display_object_actions_list` to `list_display` for your `ModelAdmin` class. See https://github.com/ninemoreminutes/django-admin-object-actions/blob/master/test_project/test_app/admin.py for an example.

I'll update the docs with that information.

**Comment by cchurch** [comment]
@atar-axis I've pushed a docs update to https://django-admin-object-actions.readthedocs.io/en/0.1.6/#usage that addresses your issue.
