### ISSUE TITLE
Do not show a form, but simply execute a function

### ISSUE THREAD

**Issue by atar-axis** [ninemoreminutes/django-admin-object-actions#8]
Hi again,
I would like to add a `print` button to each object on a given model.
When I hit this button, then I would like to print some field of this instance.

My functions looks like this:

```
    def print_card(self, request, obj):
        from django.template import loader, Context
        template = loader.get_template('print_card.html')
        content= {
            'kennung': obj.zugangscode,
            'token': obj.auth_token
        }
        return HttpResponse(template.render(content,request))
```

And my template something like this:

```
{% block content %}
    <p>Kennung: {{ kennung }}</p>
    <p>Authentifizierungstoken: {{ auth_token }}</p>
{% endblock %}
```

So I don't really need a **form**, I just want to pass the data of that instance to a template.

Is this possible?

Here is by the way a stackoverflow entry on that topic:
https://stackoverflow.com/questions/57272688/django-how-to-add-a-print-button-to-objects-to-print-some-special-fields-of-a

**Comment by cchurch** [comment]
You can specify a custom view method that can render any template or return any content you'd like. Here's the simplest example I can come up with to do that:

```python
class TestModelAdmin(ModelAdminObjectActionsMixin, admin.ModelAdmin):

    # all of the normal model admin code here

    object_actions = [
        {
            'slug': 'print',
            'verbose_name': _('Print'),
            'form_method': 'GET',
            'view': 'print_view',
        },
    ]

    def print_view(self, request, object_id, form_url='', extra_context=None, action=None):
        from django.template.response import TemplateResponse
        obj = self.get_object(request, object_id)
        return TemplateResponse(request, 'print.html', {'obj': obj})

```

Using the following template (`print.html`):

```django
<p>Name: {{ obj.name }}</p>
<p>Enabled: {{ obj.enabled }}</p>
```

**Comment by atar-axis** [comment]
That worked like a charm! Great, once again thank you very much!

**Comment by atar-axis** [comment]
I answered my own question on stackoverflow and referenced to your github site. Thank you again!
